version: 2.1

jobs:
  test_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: Catch failed steps
          command: echo "Hello Error!"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - test_error