version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/output.txt
workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]