version: 2.1

command:
  print_pipeline_id:
    description: "Prints the pipeline ID to the console"
    parameters:
      to:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>

jobs:
  printPipelineId:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID

workflows:
  pipelineIdWorkflow:
    jobs:
      - printPipelineId